version: 3.4
services:
  db:
    image: postgres
    restart: always
    ports:
      - "${DB_PORT:-5432}:5432"
    environment:
      POSTGRES_PASSWORD: "${DB_PASSWORD:-password}"
      POSTGRES_DB: "${DB_NAME:-monero-rpc}"
    volumes:
      - "${PD_DATA_DIR:~/pg}:/var/lib/postgresql/data"
  adminer:
    image: adminer
    restart: always
    ports:
      - "${DB_ADMIN_PORT:-8030}:8030"
    depends_on:
      - db
